### ISSUE TITLE
Angular 13

### ISSUE THREAD

**Issue by RodrigoRamosR** [ngxs-labs/dispatch-decorator#554]
Hello,

Is there any ETA to release a version compatible with Angular 13 dependencies?

If not, would be possible to release a new version for it?

thanks!

`Package @ngxs-labs/dispatch-decorator has an incompatible peer dependency to @angular/core (requires >=12.0.0 < 13.0.0 , would install 13.2.1)`

**Comment by RodrigoRamosR** [comment]
@arturovt @splincode @tplk @eranshmil appreciate any info, Cheers

**Comment by arturovt** [comment]
Hey, I've published v4.0.0 which is compiled with an Angular package format.

**Comment by RodrigoRamosR** [comment]
Hey @arturovt thanks for that!!!

I am still having issues to install it:

`C:\code\internal-app>npm i @ngxs-labs/dispatch-decorator@latest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: internal-app@0.0.3
npm ERR! Found: @angular/core@13.2.1
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"13.2.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@">=12.0.0 <13.0.0" from @ngxs-labs/dispatch-decorator@4.0.0
npm ERR! node_modules/@ngxs-labs/dispatch-decorator
npm ERR!   @ngxs-labs/dispatch-decorator@"4.0.0" from the root project
npm ERR!
`

It does not make sense to me, as I checked the package.json and it does point to Angular 13 core.

I already checked my npm cache , removed node_modules, package-lock, etc.

The only way to install it was using --force.
Any clue?

Another issue:
I am doing a migration since Angular v8. One by one.
The version 2.1.1 was working just fine until v11.

On Angular v12, I tried to upgrade to library 3.1.0 but I was getting this error in the browser console:
`Uncaught TypeError: setting getter-only property "\u0275fac"
    50271 main.js:17997`

Then on both, Angular v12 or v13, I could only make the application working again still using the version 2.1.1 with --force as it was dependent on older version of Angular. And it works just fine (I saw that the rxjs is the same version).

Now after install the v4.0.0, I got the same problem back.

Do you have any idea what this can be?

I didn't see anything on readme or anywhere to breaking changes or what I need to refactor to make it work with the newer versions (above 2.1.1)

Any help/info is appreciated

Thanks!
Cheers
Rod

**Comment by arturovt** [comment]
Yeah, I’ll forgotten to update peer dependencies, I’ll republish.

**Comment by RodrigoRamosR** [comment]
Hey, @arturovt, if you rereleased it, I think you will need to bump the package.json version. It still can't be installed.

Did you see my 2nd issue?

Thanks!

**Comment by arturovt** [comment]
I've published `4.0.1`.

I cannot say why you're getting this error, this package has integration tests and I haven't encountered this error either on Angular 12 or Angular 13.
